development:
  adapter: postgresql
  encoding: unicode
  database: database_development
  pool: 5
  username: postgres
  password: Patrycja25.10
    
test:
  adapter: postgresql
  encoding: unicode
  database: database_test
  pool: 5
  username: postgres
  password: Patrycja25.10
    
production:
  adapter: postgresql
  encoding: unicode
  database: database_production
  pool: 5
  username: postgres
  password: Patrycja25.10